# Generated by Django 4.2.16 on 2025-10-05 14:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outboxevent",
            name="id",
            field=models.BigAutoField(
                help_text="Auto-incrementing primary key",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for the user",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
