# Generated by Django 4.2.16 on 2025-10-06 20:50

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("expense_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categorymodel",
            options={
                "ordering": ["name", "created_at"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="expensemodel",
            options={
                "ordering": ["-expense_date", "-created_at"],
                "verbose_name": "Expense",
                "verbose_name_plural": "Expenses",
            },
        ),
        migrations.AlterModelOptions(
            name="outboxevent",
            options={
                "ordering": ["created_at", "id"],
                "verbose_name": "Outbox Event",
                "verbose_name_plural": "Outbox Events",
            },
        ),
        migrations.RemoveConstraint(
            model_name="categorymodel",
            name="expense_unique_category_per_user",
        ),
        migrations.RemoveConstraint(
            model_name="expensemodel",
            name="expense_positive_amount",
        ),
        migrations.RemoveConstraint(
            model_name="expensemodel",
            name="expense_max_amount_1m",
        ),
        migrations.RemoveIndex(
            model_name="categorymodel",
            name="expense_cat_user_name_idx",
        ),
        migrations.RenameIndex(
            model_name="categorymodel",
            new_name="em_cat_user_idx",
            old_name="expense_cat_user_idx",
        ),
        migrations.RenameIndex(
            model_name="expensemodel",
            new_name="em_exp_user_idx",
            old_name="expense_user_idx",
        ),
        migrations.RenameIndex(
            model_name="expensemodel",
            new_name="em_exp_date_idx",
            old_name="expense_date_idx",
        ),
        migrations.RenameIndex(
            model_name="expensemodel",
            new_name="em_exp_user_date_idx",
            old_name="expense_user_date_idx",
        ),
        migrations.RenameIndex(
            model_name="expensemodel",
            new_name="em_exp_user_cat_idx",
            old_name="expense_user_cat_idx",
        ),
        migrations.RenameIndex(
            model_name="outboxevent",
            new_name="em_outbox_created_idx",
            old_name="expense_outbox_created_idx",
        ),
        migrations.RenameIndex(
            model_name="outboxevent",
            new_name="em_outbox_processed_idx",
            old_name="expense_outbox_processed_idx",
        ),
        migrations.RenameIndex(
            model_name="outboxevent",
            new_name="em_outbox_type_idx",
            old_name="expense_outbox_type_idx",
        ),
        migrations.RenameIndex(
            model_name="outboxevent",
            new_name="em_outbox_aggregate_idx",
            old_name="expense_outbox_aggregate_idx",
        ),
        migrations.RemoveField(
            model_name="outboxevent",
            name="last_error",
        ),
        migrations.AddField(
            model_name="outboxevent",
            name="error_message",
            field=models.TextField(
                blank=True,
                help_text="Error message from last failed attempt",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="categorymodel",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="When the category was created",
            ),
        ),
        migrations.AlterField(
            model_name="categorymodel",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for the category",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="categorymodel",
            name="name",
            field=models.CharField(help_text="Name of the category", max_length=100),
        ),
        migrations.AlterField(
            model_name="categorymodel",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="When the category was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="categorymodel",
            name="user_id",
            field=models.UUIDField(help_text="ID of the user who owns this category"),
        ),
        migrations.AlterField(
            model_name="expensemodel",
            name="amount_tzs",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Expense amount in Tanzanian Shillings (TZS)",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="expensemodel",
            name="category_id",
            field=models.UUIDField(help_text="ID of the category for this expense"),
        ),
        migrations.AlterField(
            model_name="expensemodel",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="When the expense record was created",
            ),
        ),
        migrations.AlterField(
            model_name="expensemodel",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional description of the expense",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="expensemodel",
            name="expense_date",
            field=models.DateField(help_text="Date when the expense occurred"),
        ),
        migrations.AlterField(
            model_name="expensemodel",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for the expense",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="expensemodel",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="When the expense record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="expensemodel",
            name="user_id",
            field=models.UUIDField(help_text="ID of the user who owns this expense"),
        ),
        migrations.AlterField(
            model_name="outboxevent",
            name="aggregate_id",
            field=models.UUIDField(
                blank=True,
                help_text="ID of the aggregate that generated the event",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="outboxevent",
            name="attempts",
            field=models.IntegerField(
                default=0, help_text="Number of processing attempts"
            ),
        ),
        migrations.AlterField(
            model_name="outboxevent",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="When the event was created",
            ),
        ),
        migrations.AlterField(
            model_name="outboxevent",
            name="event_type",
            field=models.CharField(
                help_text="Type of the domain event", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="outboxevent",
            name="id",
            field=models.BigAutoField(
                help_text="Auto-incrementing event identifier",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="outboxevent",
            name="payload",
            field=models.JSONField(help_text="Event data as JSON"),
        ),
        migrations.AlterField(
            model_name="outboxevent",
            name="processed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the event was successfully processed",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="categorymodel",
            index=models.Index(fields=["name"], name="em_cat_name_idx"),
        ),
        migrations.AddIndex(
            model_name="categorymodel",
            index=models.Index(fields=["created_at"], name="em_cat_created_idx"),
        ),
        migrations.AddIndex(
            model_name="expensemodel",
            index=models.Index(fields=["category_id"], name="em_exp_category_idx"),
        ),
        migrations.AddIndex(
            model_name="expensemodel",
            index=models.Index(fields=["created_at"], name="em_exp_created_idx"),
        ),
        migrations.AddIndex(
            model_name="outboxevent",
            index=models.Index(fields=["attempts"], name="em_outbox_attempts_idx"),
        ),
        migrations.AddConstraint(
            model_name="categorymodel",
            constraint=models.UniqueConstraint(
                fields=("user_id", "name"), name="em_cat_user_name_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="expensemodel",
            constraint=models.CheckConstraint(
                check=models.Q(("amount_tzs__gte", 0)),
                name="em_exp_amount_non_negative",
            ),
        ),
        migrations.AlterModelTable(
            name="categorymodel",
            table="expense_management_categories",
        ),
        migrations.AlterModelTable(
            name="expensemodel",
            table="expense_management_expenses",
        ),
        migrations.AlterModelTable(
            name="outboxevent",
            table="expense_management_outbox_events",
        ),
    ]
